apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mockserver-poc

resources:
  - ../../base
  - mockserver-deployment.yaml
  - mockserver-service.yaml
  - mockserver-configmap.yaml
  - mockserver-pvc.yaml
  - mock-ui-deployment.yaml
  - mock-ui-service.yaml

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: alb-ingress
