apiVersion: v1
kind: ConfigMap
metadata:
  name: mockserver-public-init
data:
  initializerJson.json: |
    [
      {
        "httpRequest": {
          "path": "/.*"
        },
        "httpForward": {
          "host": "backend-public",
          "port": 80,
          "scheme": "HTTP"
        },
        "priority": 0
      }
    ]
